# Generated by Django 4.0 on 2022-11-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_curso_id_alter_inscricao_id_alter_minicurso_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inscricao',
            new_name='Aluno',
        ),
    ]
